/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_datos;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author dayan
 */
public class Actualizacion_inventario extends javax.swing.JFrame {
DefaultTableModel tabla4;
    /**
     * Creates new form Actualizacion_inventario
     */
    String op="";
    public Actualizacion_inventario() {
        initComponents();
        tabla4 = new DefaultTableModel();
        tabla4.addColumn("fechcompra");
        tabla4.addColumn("numfactura");
        tabla4.addColumn("id");
        tabla4.addColumn("cantidad");
        this.jTable1.setModel(tabla4);
        buscar_tabla("http://localhost/Appi/btn/actualizacion_buscar.php");
    }
    
    public void buscar_tabla(String x){
        try {
            // URL del API
            URL url = new URL(x);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            
            int responseCode = conn.getResponseCode();
            
            if (responseCode == HttpURLConnection.HTTP_OK) {
                BufferedReader leer = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                String inputLine;
                StringBuilder respuesta = new StringBuilder();
                
                while ((inputLine = leer.readLine()) != null) {
                    respuesta.append(inputLine);
                }
                leer.close();
                tabla4.setRowCount(0);
                JSONArray jsonArray = new JSONArray(respuesta.toString());
                
                for (int i = 0; i < jsonArray.length(); i++) {
                    JSONObject jsonObject = jsonArray.getJSONObject(i);
                    String fechcompra = jsonObject.getString("fechcompra");
                    int numfactura = jsonObject.getInt("numfactura");
                    int id = jsonObject.getInt("id");
                    int cantidad = jsonObject.getInt("cantidad");
                    
                    tabla4.addRow(new Object[]{fechcompra, numfactura, id, cantidad});
                }
            } 
            
            conn.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void entrar (String acceso){
        if (acceso.equals("insertar")){
            btnActualizar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnBuscar.setEnabled(false);
            
        }else if (acceso.equals("borrar")){
            btnActualizar.setEnabled(false);
             btnInsertar.setEnabled(false);
              btnBuscar.setEnabled(false);
            
        }else if (acceso.equals("actualizar")){
            btnInsertar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnBuscar.setEnabled(false);
            
        }else if (acceso.equals("buscar")){
            btnActualizar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnInsertar.setEnabled(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnumfactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tffechacompra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcantidad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 130, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("numero de factura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, 20));

        tfnumfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnumfacturaActionPerformed(evt);
            }
        });
        getContentPane().add(tfnumfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 200, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("fecha de compra");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 94, 150, 20));

        tffechacompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffechacompraActionPerformed(evt);
            }
        });
        getContentPane().add(tffechacompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("id");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 20));

        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 200, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 130, 20));

        tfcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcantidadActionPerformed(evt);
            }
        });
        getContentPane().add(tfcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 100, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar-flecha.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 100, -1));

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/embalaje.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 100, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/windows22 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 670, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void seleccion(String x){
        op=x;
    } 
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        menu entrar = new menu();
        entrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void tfnumfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnumfacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnumfacturaActionPerformed

    private void tffechacompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffechacompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffechacompraActionPerformed

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void tfcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcantidadActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    Metodos medo=new Metodos();
        String feco=tffechacompra.getText();
        String nufa=tfnumfactura.getText();
        String id=tfid.getText();
        String can=tfcantidad.getText();
       
        try {
            String leer=medo.gett("http://localhost/Appi/btn/actualizacion_buscar.php?numfactura="+nufa+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                    JOptionPane.showMessageDialog(this,"La actualizacion_inventario se borro");
                    medo.borrar("http://localhost/Appi/btn/actualizacion_borrar.php?numfactura="+nufa+"");
                    buscar_tabla("http://localhost/Appi/btn/actualizacion_buscar.php?");
                } else {

                   JOptionPane.showMessageDialog(this,"La actualizacion_inventario no existe");

                }
            }

        } catch (IOException ex) {
             JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Actualizacion_inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
    Metodos medo=new Metodos();
        String feco=tffechacompra.getText();
        int nufa=Integer.parseInt(tfnumfactura.getText()); 
        String id=tfid.getText();
        int can=Integer.parseInt(tfcantidad.getText());
        
        try {
            String leer=medo.gett("http://localhost/Appi/btn/actualizacion_buscar.php?numfactura="+nufa+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

               
                    String parametros="fechcompra=" + feco + "&numfactura=" + nufa + "&id=" + id + "&cantidad=" + can;
                    medo.insertar("http://localhost/Appi/btn/actualizacion_insertar.php",parametros);
                     JOptionPane.showMessageDialog(this,"El registro se guardado correctamente");

                
            }
         buscar_tabla("http://localhost/Appi/btn/actualizacion_buscar.php?");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Actualizacion_inventario.class.getName()).log(Level.SEVERE, null, ex);
        }             
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    Metodos medo=new Metodos();
        String feco=tffechacompra.getText();
        String nufa=tfnumfactura.getText();
        String id=tfid.getText();
        String can=tfcantidad.getText();
        
        try {
            String leer=medo.gett("http://localhost/Appi/btn/actualizacion_buscar.php?numfactura="+nufa+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                   buscar_tabla("http://localhost/Appi/btn/actualizacion_buscar.php?numfactura="+nufa+"");
                } else {
                   JOptionPane.showMessageDialog(this,"El registro no existe");
                }
            }

        } catch (IOException ex) {
            System.out.println("error");
            Logger.getLogger(Actualizacion_inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     Metodos medo=new Metodos();
        String feco=tffechacompra.getText();
        String nufa=tfnumfactura.getText();
        String id=tfid.getText();
        String can=tfcantidad.getText();
        
        try {
            String leer=medo.gett("http://localhost/Appi/btn/actualizacion_buscar.php?numfactura="+nufa+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                     JOptionPane.showMessageDialog(this,"El registro se actualizo correctamente");
                    medo.actualizar("http://localhost/Appi/btn/actualizacion_actualizar.php?fechcompra="+feco+"&numfactura="+nufa+"&id="+id+"&cantidad="+can);
                    
                } else {

                     JOptionPane.showMessageDialog(this,"El registro no existe");

                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Actualizacion_inventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizacion_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizacion_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizacion_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizacion_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizacion_inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField tfcantidad;
    private javax.swing.JTextField tffechacompra;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfnumfactura;
    // End of variables declaration//GEN-END:variables
}
