/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Base_de_datos;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author dayan
 */
public class Registro_productos extends javax.swing.JFrame {
DefaultTableModel tabla1;
    /**
     * Creates new form Registro_productos
     */
    String op="";
    public Registro_productos() {
        initComponents();
        //jalar los datos de la base de datos a la tabla para mostrar los datos que tenemos en la base de datos
        tabla1 = new DefaultTableModel();
        tabla1.addColumn("id");
        tabla1.addColumn("nombre producto");
        tabla1.addColumn("marca");
        tabla1.addColumn("presentacion");
        tabla1.addColumn("precio");
        this.jTable1.setModel(tabla1);
        buscar_tabla("http://localhost/Appi/btn/registro_buscar.php");
    }
    public void buscar_id(){
        int columnaId = 0; 
        int numeroMaximo = 0;
        for (int fila = 0; fila < tabla1.getRowCount(); fila++) {
                int valorActual = (int) tabla1.getValueAt(fila, columnaId);
                if (valorActual > numeroMaximo) {
                     numeroMaximo = valorActual;
                }
        }
        if (numeroMaximo==0){
            numeroMaximo=100;
        }
        int nuevoNumero = numeroMaximo + 1;
        tfid.setText(String.valueOf(nuevoNumero));
    }
    public void buscar_tabla(String x){
        try {
            // URL del API
            URL url = new URL(x);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            
            int responseCode = conn.getResponseCode();
            
            if (responseCode == HttpURLConnection.HTTP_OK) {
                BufferedReader leer = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                String inputLine;
                StringBuilder respuesta = new StringBuilder();
                
                while ((inputLine = leer.readLine()) != null) {
                    respuesta.append(inputLine);
                }
                leer.close();
                tabla1.setRowCount(0);
                JSONArray jsonArray = new JSONArray(respuesta.toString());
                
                for (int i = 0; i < jsonArray.length(); i++) {
                    JSONObject jsonObject = jsonArray.getJSONObject(i);
                    int id = jsonObject.getInt("id");
                    String nombre = jsonObject.getString("nombre");
                    String marca = jsonObject.getString("marca");
                    String presentacion = jsonObject.getString("presentacion");
                    int precio = jsonObject.getInt("precio");
                    
                    tabla1.addRow(new Object[]{id, nombre, marca, presentacion, precio});
                }
            }
            
            conn.disconnect();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //restricciones 
    public void entrar (String acceso){
        if (acceso.equals("insertar")){
            btnActualizar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnBuscar.setEnabled(false);
            tfid.setEnabled(false);
            buscar_id();
        }else if (acceso.equals("borrar")){
            btnActualizar.setEnabled(false);
             btnInsertar.setEnabled(false);
              btnBuscar.setEnabled(false);
            
        }else if (acceso.equals("actualizar")){
            btnInsertar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnBuscar.setEnabled(false);
            
        }else if (acceso.equals("buscar")){
            btnActualizar.setEnabled(false);
             btnBorrar.setEnabled(false);
              btnInsertar.setEnabled(false);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfpresentacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfprecio = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 20));

        tfnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnombreActionPerformed(evt);
            }
        });
        getContentPane().add(tfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 200, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 20));

        tfid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidActionPerformed(evt);
            }
        });
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 200, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("marca");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 20));

        tfmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(tfmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 200, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("presentacion");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 20));

        tfpresentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpresentacionActionPerformed(evt);
            }
        });
        getContentPane().add(tfpresentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 200, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 20));

        tfprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfprecioActionPerformed(evt);
            }
        });
        getContentPane().add(tfprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 30));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 100, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar-flecha.png"))); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 100, -1));

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/embalaje.png"))); // NOI18N
        btnInsertar.setText("insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 620, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/windows22 (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        menu entrar = new menu();
        entrar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void tfnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnombreActionPerformed

    private void tfidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidActionPerformed

    private void tfmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmarcaActionPerformed

    private void tfpresentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpresentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpresentacionActionPerformed

    private void tfprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfprecioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    //busqueda de los datos que estan registrados en la base de datos
        Metodos medo=new Metodos();
        String id=tfid.getText();
        String num=tfnombre.getText();
        String mar=tfmarca.getText();
        String present=tfpresentacion.getText();
        String prec=tfprecio.getText();
        try {
            String leer=medo.gett("http://localhost/Appi/btn/registro_buscar.php?id="+id+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                   buscar_tabla("http://localhost/Appi/btn/registro_buscar.php?id="+id+"");
                } else {
                   JOptionPane.showMessageDialog(this,"El registro_productos no existe");
                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Registro_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
       //para buscar si los datos que quieres agregar ya existen u agregarlos
        Metodos medo=new Metodos();
        String id=tfid.getText();
        String num=tfnombre.getText();
        String mar=tfmarca.getText();
        String present=tfpresentacion.getText();
        String prec=tfprecio.getText();
        try {
            String leer=medo.gett("http://localhost/Appi/btn/registro_buscar.php?id="+id+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                   JOptionPane.showMessageDialog(this,"El registro_productos ya existe");
                } else {

                    medo.insertar("http://localhost/Appi/btn/productos-registro_insertar.php", "id="+id+"&nombre="+num+"&marca="+mar+"&presentacion="+present+"&precio="+prec);
                   JOptionPane.showMessageDialog(this,"El registro_productos se guardado correctamente");
                   tfmarca.setText("");
                   tfnombre.setText("");
                   tfprecio.setText("");
                   tfpresentacion.setText("");
                }
            }
            buscar_tabla("http://localhost/Appi/btn/registro_buscar.php?");
            buscar_id();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Registro_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    //busca en la base de datos ya esta sea existente se borrara de la base de datos
        Metodos medo=new Metodos();
        String id=tfid.getText();
        String num=tfnombre.getText();
        String mar=tfmarca.getText();
        String present=tfpresentacion.getText();
        String prec=tfprecio.getText();
        try {
            String leer=medo.gett("http://localhost/Appi/btn/registro_buscar.php?id="+id+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                     JOptionPane.showMessageDialog(this,"El registro_productos se borro");
                    medo.borrar("http://localhost/Appi/btn/productos-registro_borrar.php?id="+id+"");
                } else {

                    JOptionPane.showMessageDialog(this,"El producto no existe");

                }
            }
    buscar_tabla("http://localhost/Appi/btn/registro_buscar.php?");
        
        } catch (IOException ex) {
           JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Registro_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      //la actualizacion de cualquier dato que este registrada en nuestra base de datos
        Metodos medo=new Metodos();
        String id=tfid.getText();
        String num=tfnombre.getText();
        String mar=tfmarca.getText();
        String present=tfpresentacion.getText();
        String prec=tfprecio.getText();
        try {
            String leer=medo.gett("http://localhost/Appi/btn/registro_buscar.php?id="+id+"");
            if (leer != null) {
                JSONArray J= new JSONArray(leer);

                if (J.length() > 0) {
                     JOptionPane.showMessageDialog(this,"El registro_productos se actualizo correctamente");
                    medo.actualizar("http://localhost/Appi/btn/registro_actualizar.php?id="+id+"&nombre="+num+"&marca="+mar+"&presentacion="+present+"&precio="+prec);
                    
                } else {

                    JOptionPane.showMessageDialog(this,"El registro_productos no existe");

                }
            }

        } catch (IOException ex) {
             JOptionPane.showMessageDialog(this,"error");
            Logger.getLogger(Registro_productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfmarca;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField tfprecio;
    private javax.swing.JTextField tfpresentacion;
    // End of variables declaration//GEN-END:variables
}
